//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.11.05 at 05:34:53 PM CET
//

package de.quinscape.intrexx.report.transport.jaxb.v1;

import java.util.*;

import javax.xml.bind.annotation.*;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * {@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="http://www.w3.org/2001/XMLSchema#anyType">
 *       <sequence>
 *         <element ref="http://www.quinscape.de/intrexx/reports#report" maxOccurs="unbounded"/>
 *         <element ref="http://www.quinscape.de/intrexx/reports#resource" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *       <attribute name="version" type="http://www.w3.org/2001/XMLSchema#float" />
 *       <attribute name="comment" type="http://www.w3.org/2001/XMLSchema#string" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
                                 "reports",
                                 "resources"
})
@XmlRootElement(name = "export")
public class Export
{

  @XmlElement(name = "report", required = true)
  protected List<Report> reports;

  @XmlElement(name = "resource")
  protected List<Resource> resources;

  @XmlAttribute(name = "version")
  protected Float version;

  @XmlAttribute(name = "comment")
  protected String comment;

  /**
   * Gets the value of the reports property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the reports property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getReports().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link Report }
   * 
   * 
   */
  public List<Report> getReports()
  {
    if(reports == null)
    {
      reports = new ArrayList<Report>();
    }
    return this.reports;
  }

  /**
   * Gets the value of the resources property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the resources property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getResources().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link Resource }
   * 
   * 
   */
  public List<Resource> getResources()
  {
    if(resources == null)
    {
      resources = new ArrayList<Resource>();
    }
    return this.resources;
  }

  /**
   * Gets the value of the version property.
   * 
   * @return
   *         possible object is {@link Float }
   * 
   */
  public Float getVersion()
  {
    return version;
  }

  /**
   * Sets the value of the version property.
   * 
   * @param value
   *          allowed object is {@link Float }
   * 
   */
  public void setVersion(Float value)
  {
    this.version = value;
  }

  /**
   * Gets the value of the comment property.
   * 
   * @return
   *         possible object is {@link String }
   * 
   */
  public String getComment()
  {
    return comment;
  }

  /**
   * Sets the value of the comment property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setComment(String value)
  {
    this.comment = value;
  }

}
