//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.11.05 at 05:34:53 PM CET
//

package de.quinscape.intrexx.report.transport.jaxb.v1;

import javax.xml.bind.annotation.*;

/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the de.quinscape.intrexx.report.transport.jaxb.v1 package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation
 * for XML content. The Java representation of XML content can consist of schema derived interfaces
 * and classes representing the binding of schema type definitions, element declarations and model
 * groups. Factory methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory
{

  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes
   * for package: de.quinscape.intrexx.report.transport.jaxb.v1
   * 
   */
  public ObjectFactory()
  {}

  /**
   * Create an instance of {@link Export }
   * 
   */
  public Export createExport()
  {
    return new Export();
  }

  /**
   * Create an instance of {@link Report }
   * 
   */
  public Report createReport()
  {
    return new Report();
  }

  /**
   * Create an instance of {@link ReportResource }
   * 
   */
  public ReportResource createReportResource()
  {
    return new ReportResource();
  }

  /**
   * Create an instance of {@link Resource }
   * 
   */
  public Resource createResource()
  {
    return new Resource();
  }

}
