//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.05 at 05:34:53 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.quinscape.de/intrexx/reports", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.quinscape.intrexx.report.transport.jaxb.v1;
