//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.05 at 05:34:53 PM CET 
//


package de.quinscape.intrexx.report.transport.jaxb.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * {@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="http://www.w3.org/2001/XMLSchema#anyType">
 *       <sequence>
 *         <element name="resource" type="http://www.quinscape.de/intrexx/reports#reportResource" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *       <attribute name="guid" type="http://www.quinscape.de/intrexx/reports#ix-guid" />
 *       <attribute name="permissions" type="http://www.quinscape.de/intrexx/reports#ix-str" />
 *       <attribute name="name" type="http://www.quinscape.de/intrexx/reports#ix-str" />
 *       <attribute name="default_connection" type="http://www.quinscape.de/intrexx/reports#ix-str" />
 *       <attribute name="beschreibung" type="http://www.quinscape.de/intrexx/reports#ix-str" />
 *       <attribute name="ref_main_report" type="http://www.quinscape.de/intrexx/reports#ix-guid" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "resources"
})
@XmlRootElement(name = "report")
public class Report {

    @XmlElement(name = "resource", namespace = "")
    protected List<ReportResource> resources;
    @XmlAttribute(name = "guid")
    protected String guid;
    @XmlAttribute(name = "permissions")
    protected String permissions;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "default_connection")
    protected String defaultConnection;
    @XmlAttribute(name = "beschreibung")
    protected String beschreibung;
    @XmlAttribute(name = "ref_main_report")
    protected String refMainReport;

    /**
     * Gets the value of the resources property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resources property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResources().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReportResource }
     * 
     * 
     */
    public List<ReportResource> getResources() {
        if (resources == null) {
            resources = new ArrayList<ReportResource>();
        }
        return this.resources;
    }

    /**
     * Gets the value of the guid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuid() {
        return guid;
    }

    /**
     * Sets the value of the guid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuid(String value) {
        this.guid = value;
    }

    /**
     * Gets the value of the permissions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPermissions() {
        return permissions;
    }

    /**
     * Sets the value of the permissions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPermissions(String value) {
        this.permissions = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the defaultConnection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultConnection() {
        return defaultConnection;
    }

    /**
     * Sets the value of the defaultConnection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultConnection(String value) {
        this.defaultConnection = value;
    }

    /**
     * Gets the value of the beschreibung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeschreibung() {
        return beschreibung;
    }

    /**
     * Sets the value of the beschreibung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeschreibung(String value) {
        this.beschreibung = value;
    }

    /**
     * Gets the value of the refMainReport property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefMainReport() {
        return refMainReport;
    }

    /**
     * Sets the value of the refMainReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefMainReport(String value) {
        this.refMainReport = value;
    }

}
