//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.11.05 at 05:34:53 PM CET
//

package de.quinscape.intrexx.report.transport.jaxb.v1;

import javax.xml.bind.annotation.*;

/**
 * <p>
 * Java class for reportResource complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * {@code
 * <complexType name="reportResource">
 *   <complexContent>
 *     <restriction base="http://www.w3.org/2001/XMLSchema#anyType">
 *       <attribute name="guid" type="http://www.quinscape.de/intrexx/reports#ix-guid" />
 *       <attribute name="ref_resource" type="http://www.quinscape.de/intrexx/reports#ix-str" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reportResource")
public class ReportResource
{

  @XmlAttribute(name = "guid")
  protected String guid;

  @XmlAttribute(name = "ref_resource")
  protected String refResource;

  /**
   * Gets the value of the guid property.
   * 
   * @return
   *         possible object is {@link String }
   * 
   */
  public String getGuid()
  {
    return guid;
  }

  /**
   * Sets the value of the guid property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setGuid(String value)
  {
    this.guid = value;
  }

  /**
   * Gets the value of the refResource property.
   * 
   * @return
   *         possible object is {@link String }
   * 
   */
  public String getRefResource()
  {
    return refResource;
  }

  /**
   * Sets the value of the refResource property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setRefResource(String value)
  {
    this.refResource = value;
  }

}
