//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.11.05 at 05:34:53 PM CET
//

package de.quinscape.intrexx.report.transport.jaxb.v1;

import javax.xml.bind.annotation.*;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * {@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="http://www.w3.org/2001/XMLSchema#anyType">
 *       <attribute name="guid" type="http://www.quinscape.de/intrexx/reports#ix-guid" />
 *       <attribute name="name" type="http://www.quinscape.de/intrexx/reports#ix-str" />
 *       <attribute name="filename" type="http://www.quinscape.de/intrexx/reports#ix-str" />
 *       <attribute name="url" type="http://www.quinscape.de/intrexx/reports#ix-str" />
 *       <attribute name="md5" type="http://www.quinscape.de/intrexx/reports#md5-str" />
 *       <attribute name="size" type="http://www.w3.org/2001/XMLSchema#long" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "resource")
public class Resource
{

  @XmlAttribute(name = "guid")
  protected String guid;

  @XmlAttribute(name = "name")
  protected String name;

  @XmlAttribute(name = "filename")
  protected String filename;

  @XmlAttribute(name = "url")
  protected String url;

  @XmlAttribute(name = "md5")
  protected String md5;

  @XmlAttribute(name = "size")
  protected Long size;

  /**
   * Gets the value of the guid property.
   * 
   * @return
   *         possible object is {@link String }
   * 
   */
  public String getGuid()
  {
    return guid;
  }

  /**
   * Sets the value of the guid property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setGuid(String value)
  {
    this.guid = value;
  }

  /**
   * Gets the value of the name property.
   * 
   * @return
   *         possible object is {@link String }
   * 
   */
  public String getName()
  {
    return name;
  }

  /**
   * Sets the value of the name property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setName(String value)
  {
    this.name = value;
  }

  /**
   * Gets the value of the filename property.
   * 
   * @return
   *         possible object is {@link String }
   * 
   */
  public String getFilename()
  {
    return filename;
  }

  /**
   * Sets the value of the filename property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setFilename(String value)
  {
    this.filename = value;
  }

  /**
   * Gets the value of the url property.
   * 
   * @return
   *         possible object is {@link String }
   * 
   */
  public String getUrl()
  {
    return url;
  }

  /**
   * Sets the value of the url property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setUrl(String value)
  {
    this.url = value;
  }

  /**
   * Gets the value of the md5 property.
   * 
   * @return
   *         possible object is {@link String }
   * 
   */
  public String getMd5()
  {
    return md5;
  }

  /**
   * Sets the value of the md5 property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setMd5(String value)
  {
    this.md5 = value;
  }

  /**
   * Gets the value of the size property.
   * 
   * @return
   *         possible object is {@link Long }
   * 
   */
  public Long getSize()
  {
    return size;
  }

  /**
   * Sets the value of the size property.
   * 
   * @param value
   *          allowed object is {@link Long }
   * 
   */
  public void setSize(Long value)
  {
    this.size = value;
  }
}
